"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['./src/face_id_main.py']
DATA_FILES = ['./src/models/lfw_classifier.pkl', './src/models/pretrained_facenet_model_20180402-114759.pb']
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
