"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['face_id_main.py']
DATA_FILES = ['./models/pretrained_facenet_model_20180402-114759.pb', './models/lfw_classifier.pkl']
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
